### ISSUE TITLE
Set up Power BI Project (.pbip) baseline

### ISSUE THREAD

**Issue by LarsKemmann** [CareTogether/CareTogether-PowerBI#1]
Initial task list:

- [x] Save the baseline `.pbix` file I emailed you as `.pbip` in the root of this repository (update the existing empty `.gitignore` file) (see [docs](https://learn.microsoft.com/en-us/power-bi/developer/projects/projects-overview))
- [x] Open the Power BI Project and ensure you can refresh data from production with the research credentials, without the `cache.abf`
- [x] Get [CareTogetherCMS](https://github.com/CareTogether/CareTogetherCMS/) running locally and try refreshing data from the local environment (change the `Production` parameter from `TRUE` to `FALSE`). Verify that adding a family, for example, or other actions are reflected in the updated data in Power BI.
- [x] Add a GitHub code owner file that specifies my username (`LarsKemmann`) as a code owner to ensure I'm automatically required for PR reviews -- copy from [this one](https://github.com/CareTogether/CareTogetherCMS/blob/main/.github/CODEOWNERS)
- [x] Push a branch and create a pull request against the _main_ branch

**Comment by marcusgraca** [comment]
Waiting for the merge into the main branch
