### ISSUE TITLE
Extend Family engagement measures & visuals to Person

### ISSUE THREAD

**Issue by LarsKemmann** [CareTogether/CareTogether-PowerBI#10]
Duplicate the `Family` engagement logic as new measures (and optionally a new page, or new visuals) to calculate the same `# of People Engaged`, `Last Engaged` date, etc. measures for the `Person` table.

**Comment by marcusgraca** [comment]
After validating the results, I noticed something unusual when using the relationships between the tables. However, after slightly adjusting the relationships, I was able to achieve the expected results without adding any additional columns.

**Comment by marcusgraca** [comment]
Added the measures:

- # of Engaged People;
- Individual Engagement Level 
- Individual Last Arrangement End Date =
