### ISSUE TITLE
Add in the "# of Families Engaged" measure and sample report

### ISSUE THREAD

**Issue by LarsKemmann** [CareTogether/CareTogether-PowerBI#2]
Use the version you came up with previously. This will be our first chance to test the PR process for reviewing code changes to the semantic model and report pages.

Copy in the previous code updates from the coding exercise (including a demo page).

**Comment by marcusgraca** [comment]
Added 'Family Engagement' tab. Two new measures added: # of Engaged Families and # of Approved Families.

**Comment by marcusgraca** [comment]
Waiting for the merge into the main.
