### ISSUE TITLE
Identify level of engagement and date of most recent engagement by family

### ISSUE THREAD

**Issue by LarsKemmann** [CareTogether/CareTogether-PowerBI#9]
#2 is a prerequisite.

Tasks for this issue:

- [x] **New Requirement:** Identify the "level" of engagement for each family during the given timeframe. This is basically counting the # of assignments that the family has, as opposed to just seeing if they have any assignments in the given timeframe or not.
- [x] **New Requirement:** Identify the most recent engagement for each family. For each family, identify the most recent end date of all of the arrangements that they were assigned to during the given timeframe. If an arrangement is still open, treat that as `TODAY()`, i.e., the family is currently assigned.

You can submit a draft PR with multiple commits to track your progress here, but there should probably be one PR that addresses both requirements.

**Comment by marcusgraca** [comment]
To calculate the "Arrangement Last Date", it was necessary to bring the timeframe into the "Family Function Assignment Table. With this approach, we have a function formula with good results; however, I will continue testing alternatives to avoid this column duplication.
